from tkinter import *
from tkinter.ttk import *
w=Tk()
w.title("Registration screen")
w.geometry("720x720")
w.configure(background="Light blue")
fn=Label(w,text="First name",font=("calibri",12)).grid(row=0,column=0)
ln=Label(w,text="Last name",font=("calibri",12)).grid(row=1,column=0)
ei=Label(w,text="Email id",font=("calibri",12)).grid(row=2,column=0)
cn=Label(w,text="Contact number",font=("calibri",12)).grid(row=3,column=0)
Mn=Label(w,text="Mother's name",font=("calibri",12)).grid(row=4,column=0)
Fn=Label(w,text="Father's name",font=("calibri",12)).grid(row=5,column=0)
add=Label(w,text="Address",font=("calibri",12)).grid(row=6,column=0)
eq=Label(w,text="Educational qualification",font=("calibri",12)).grid(row=7,column=0)
ej=Label(w,text="Year of joining",font=("calibri",12)).grid(row=8,column=0)
ms=Label(w,text="Martial status ",font=("calibri",12)).grid(row=9,column=0)
b=Button(w,text="Submit").grid(row=10,column=0)
fn1=Entry(w).grid(row=0,column=1)
ln1=Entry(w).grid(row=1,column=1)
ei1=Entry(w).grid(row=2,column=1)
cn1=Entry(w).grid(row=3,column=1)
Mn1=Entry(w).grid(row=4,column=1)
Fn1=Entry(w).grid(row=5,column=1)
add1=Entry(w,width=20).grid(row=6,column=1)
eq1=Entry(w).grid(row=7,column=1)
c=Combobox(w)
c["values"]=(2020,2021,2022,2023,2024,2025,2025,2026,2027,2028)
c.grid(row=8,column=1)
r1=Radiobutton(w,text="Single",value=0).grid(row=9,column=1)
r2=Radiobutton(w,text="Married",value=1).grid(row=9,column=2)
w.mainloop()

